name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run Jest tests
        run: npm run test
      - name: Run ESLint
        run: npm run lint
      - name: Test frontend jest tests
        run: npm run coverage
        working-directory: src
      - name: Data to codecov
        run: bash <(curl -s https://codecov.io/bash)

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          PORT: ${{ secrets.PORT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          TABLE: ${{ secrets.TABLE }}
          TABLE_DEV: ${{ secrets.TABLE_DEV }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          file_name: .env

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Deploy to AWS
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name user-api-deployer \
            --deployment-group-name KSD \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
