name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanoeb/eslint-action@1.0.2

      - name: Install dependencies
        run: npm ci
      - name: Run Jest tests
        run: npm run test
